AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ImageName:
    Type: String
  ImageTag:
    Type: String

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      ImageUri: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ImageName}:${ImageTag}