AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Name:
    Type: String

Resources:
  Repository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref Name

Outputs:
  RepositoryName:
    Value: !Ref Repository
  RepositoryHost:
    Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com