name: Deployment

on:
  release:
    types: ['created']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Parse the current version
        id: version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - uses: chrnorm/deployment-action@releases/v1
        name: Create Deployment
        id: deployment
        with:
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN}}
          environment: production

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registries: 420048798477,628053151772

      - name: Deploy Docker image
        env:
          VERSION: ${{ steps.version.outputs.VERSION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: make build

      - name: Update Deployment (success)
        if: success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          state: 'success'
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
