name: Deployment

on:
  release:
    types: ['created']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Parse the current version
        id: version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Deploy Docker image
        run: VERSION=${{ steps.get_version.outputs.VERSION }} make build
