name: Release

on:
  deployment_status

jobs:
  release:
    runs-on: ubuntu-latest


    steps:
      - name: Parse the current version
        id: version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Update AWS Lambda
        run: echo "Use tag ${{ steps.version.outputs.VERSION }}"
